{
 "title": "ShopFlow — Métriques Prometheus",
 "tags": [
  "shopflow",
  "tp2",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Taux d'erreur 5xx (%)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(100 * sum(rate(http_requests_total{job=\"app-sample\", status=~\"5..\"}[5m])) / sum(rate(http_requests_total{job=\"app-sample\"}[5m]))) or vector(0)"
    }
   ]
  },
  {
   "title": "DB Pool — saturation",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "db_connections_active{job=\"app-sample\"} / 50"
    }
   ]
  },
  {
   "title": "Latence checkout — P50 / P95 / P99",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 7, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "legendFormat": "P50",
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"app-sample\", endpoint=\"/api/checkout\"}[5m])) by (le))"
    },
    {
     "legendFormat": "P95",
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"app-sample\", endpoint=\"/api/checkout\"}[5m])) by (le))"
    },
    {
     "legendFormat": "P99",
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{job=\"app-sample\", endpoint=\"/api/checkout\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Débit (req/s) par endpoint",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 7, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "legendFormat": "{{endpoint}}",
     "expr": "sum by (endpoint) (rate(http_requests_total{job=\"app-sample\"}[5m]))"
    }
   ]
  }
 ]
}